copy Identifier.hpp      %PROJINC%
copy MekTek.hpp          %PROJINC%
copy UserKey.hpp         %PROJINC%
copy UserKey.ipp         %PROJINC%
copy Registration.hpp    %PROJINC%
copy Registration.ipp    %PROJINC%
copy ParserIndicator.hpp %PROJINC%
copy ParserIndicator.ipp %PROJINC%
copy CurrentDate.hpp     %PROJINC%
copy ExpirationDate.hpp  %PROJINC%
copy ExpirationDate.ipp  %PROJINC%
copy Distance.hpp        %PROJINC%
copy Distance.ipp        %PROJINC%
copy FontInfo.hpp        %PROJINC%
copy FontInfo.ipp        %PROJINC%
copy Generator.hpp       %PROJINC%
copy Generator.ipp       %PROJINC%
copy Gin.hpp             %PROJINC%
copy Gin.ipp             %PROJINC%
copy Symbol.hpp          %PROJINC%
copy Symbol.ipp          %PROJINC%
copy CodePage.hpp        %PROJINC%
copy CodePage.ipp        %PROJINC%
copy TraceGenerator.hpp  %PROJINC%
copy HeaderGenerator.hpp %PROJINC%
copy TextGenerator.hpp   %PROJINC%
copy WindowDef.hpp       %PROJINC%
copy WindowDef.ipp       %PROJINC%
copy ArtDef.hpp          %PROJINC%
copy ArtDef.ipp          %PROJINC%
copy ArtSet.hpp          %PROJINC%
copy Parser.hpp          %PROJINC%
copy Parser.ipp          %PROJINC%
copy TextParser.hpp      %PROJINC%
copy Filename.hpp        %PROJINC%
copy EnhancedYacc.hpp    %PROJINC%
copy CDefineYacc.hpp     %PROJINC%
copy ParserIndicator.hpp %PROJINC%
copy ParserIndicator.ipp %PROJINC%
copy ParserException.hpp %PROJINC%
copy gen.lib %PROJOBJ%
copy *.llr %PROJTAB%
copy *.dfa %PROJTAB%
