copy ArtItem.hpp %PROJINC%
copy ArtItem.ipp %PROJINC%
copy LinkItem.hpp %PROJINC%
copy LinkItem.ipp %PROJINC%
copy FlowGenerator.hpp %PROJINC%
copy FlowGeneratorContext.hpp %PROJINC%
copy BoldItem.hpp %PROJINC%
copy FlowItem.hpp %PROJINC%
copy FontItem.hpp %PROJINC%
copy ItalicItem.hpp %PROJINC%
copy Item.hpp %PROJINC%
copy NewLineItem.hpp %PROJINC%
copy ParagraphItem.hpp %PROJINC%
copy PopItem.hpp %PROJINC%
copy PopItem.ipp %PROJINC%
copy PushItem.hpp %PROJINC%
copy PushItem.ipp %PROJINC%
copy SymbolItem.hpp %PROJINC%
copy UnderlineItem.hpp %PROJINC%
copy BoldItem.ipp %PROJINC%
copy FlowItem.ipp %PROJINC%
copy FontItem.ipp %PROJINC%
copy ItalicItem.ipp %PROJINC%
copy Item.ipp %PROJINC%
copy SpaceItem.hpp %PROJINC%
copy SymbolItem.ipp %PROJINC%
copy UnderlineItem.ipp %PROJINC%
copy WordItem.hpp %PROJINC%
copy WordItem.ipp %PROJINC%
copy ItemCursor.hpp %PROJINC%
copy ItemSequence.hpp %PROJINC%
copy OrderedItemCursor.hpp %PROJINC%
copy OrderedItemCursor.ipp %PROJINC%
copy Editor.hpp %PROJINC%
copy Editor.ipp %PROJINC%
copy Kursor.hpp %PROJINC%
copy Page.hpp %PROJINC%
copy Page.ipp %PROJINC%
copy PlacedView.hpp %PROJINC%
copy PlacedView.ipp %PROJINC%
copy View.hpp %PROJINC%
copy View.ipp %PROJINC%
copy SubjectView.hpp %PROJINC%
copy SubjectView.ipp %PROJINC%
copy PenState.hpp %PROJINC%
copy PenState.ipp %PROJINC%
copy EditorCursor.hpp %PROJINC%
copy EditorCursor.ipp %PROJINC%
copy Types.hpp %PROJINC%
copy vydit.h %PROJINC%
copy vydit.lib %PROJLIB%
copy vydit.dll %PROJDLL%
