
all: \
    .\htmlgen.lib

.\HtmlSymbols.asm .\HtmlSymbols.obj: \
    d:\proj\HtmlGenerator\HtmlSymbols.cpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlTag.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlTag.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlCommon.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}MekTek.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlGenerator.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlContext.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Generator.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}CodePage.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Registration.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}CurrentDate.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}WindowDef.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}ArtDef.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Gin.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Generator.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}CodePage.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}UserKey.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Registration.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Distance.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}WindowDef.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}ArtDef.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Symbol.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}FontInfo.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Gin.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}ExpirationDate.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}UserKey.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Distance.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Symbol.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}FontInfo.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}ExpirationDate.ipp

.\HtmlSend.asm .\HtmlSend.obj: \
    d:\proj\HtmlGenerator\HtmlSend.cpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlTag.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlTag.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlCommon.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}MekTek.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlGenerator.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlContext.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Generator.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}CodePage.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Registration.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}CurrentDate.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}WindowDef.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}ArtDef.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Gin.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Generator.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}CodePage.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}UserKey.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Registration.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Distance.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}WindowDef.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}ArtDef.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Symbol.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}FontInfo.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Gin.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}ExpirationDate.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}UserKey.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Distance.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Symbol.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}FontInfo.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}ExpirationDate.ipp

.\HtmlParaStyle.asm .\HtmlParaStyle.obj: \
    d:\proj\HtmlGenerator\HtmlParaStyle.cpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlTag.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlTag.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlCommon.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}MekTek.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlGenerator.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlContext.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Generator.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}CodePage.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Registration.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}CurrentDate.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}WindowDef.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}ArtDef.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Gin.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Generator.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}CodePage.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}UserKey.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Registration.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Distance.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}WindowDef.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}ArtDef.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Symbol.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}FontInfo.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Gin.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}ExpirationDate.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}UserKey.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Distance.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Symbol.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}FontInfo.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}ExpirationDate.ipp

.\HtmlGenerator.asm .\HtmlGenerator.obj: \
    d:\proj\HtmlGenerator\HtmlGenerator.cpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlTag.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlTag.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlCommon.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}MekTek.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlGenerator.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlContext.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Generator.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}CodePage.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Registration.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}CurrentDate.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}WindowDef.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}ArtDef.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Gin.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Generator.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}CodePage.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}UserKey.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Registration.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Distance.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}WindowDef.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}ArtDef.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Symbol.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}FontInfo.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Gin.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}ExpirationDate.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}UserKey.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Distance.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Symbol.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}FontInfo.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}ExpirationDate.ipp

.\HtmlControl.asm .\HtmlControl.obj: \
    d:\proj\HtmlGenerator\HtmlControl.cpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlTag.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlTag.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlCommon.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}MekTek.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlGenerator.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlContext.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Generator.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}CodePage.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Registration.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}CurrentDate.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}WindowDef.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}ArtDef.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Gin.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Generator.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}CodePage.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}UserKey.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Registration.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Distance.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}WindowDef.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}ArtDef.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Symbol.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}FontInfo.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Gin.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}ExpirationDate.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}UserKey.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Distance.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Symbol.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}FontInfo.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}ExpirationDate.ipp

.\HtmlContext.asm .\HtmlContext.obj: \
    d:\proj\HtmlGenerator\HtmlContext.cpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlTag.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlTag.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlCommon.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}MekTek.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlGenerator.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlContext.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Generator.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}CodePage.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Registration.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}CurrentDate.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}WindowDef.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}ArtDef.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Gin.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Generator.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}CodePage.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}UserKey.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Registration.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Distance.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}WindowDef.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}ArtDef.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Symbol.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}FontInfo.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Gin.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}ExpirationDate.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}UserKey.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Distance.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Symbol.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}FontInfo.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}ExpirationDate.ipp

.\HtmlCharStyle.asm .\HtmlCharStyle.obj: \
    d:\proj\HtmlGenerator\HtmlCharStyle.cpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlTag.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlTag.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlCommon.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}MekTek.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlGenerator.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlContext.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Generator.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}CodePage.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Registration.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}CurrentDate.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}WindowDef.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}ArtDef.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Gin.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Generator.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}CodePage.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}UserKey.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Registration.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Distance.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}WindowDef.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}ArtDef.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Symbol.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}FontInfo.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Gin.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}ExpirationDate.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}UserKey.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Distance.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}Symbol.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}FontInfo.ipp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}ExpirationDate.ipp

.\HtmlTag.asm .\HtmlTag.obj: \
    d:\proj\HtmlGenerator\HtmlTag.cpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlTag.hpp \
    {d:\proj\HtmlGenerator;$(INCLUDE);}HtmlTag.ipp
