/*******************************************************************************
* FILE NAME: CloseHandler.hpp                                                  *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Declaration of the class:                                                  *
*     CloseHandler- Intercept close command                                    *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _CLOSEHANDLER_
#define _CLOSEHANDLER_

class CloseHandler;

// required include files, added manually!
#ifndef _VYPER_
#include "Vyper.hpp"
#endif

#ifndef _ICMDHDR_
#include <icmdhdr.hpp>
#endif

#ifndef _ISYSMENU_
#include <isysmenu.hpp>
#endif
// end required include files

#include "CloseHandler.h"


/*----------------------------------------------------------------------------*/
/* Align classes on four byte boundary.                                       */
/*----------------------------------------------------------------------------*/
#pragma pack(4)

//*****************************************************************************
// Class definition for CloseHandler
//*****************************************************************************
class CloseHandler : public ICommandHandler {
public:
protected:
private:

#include "CloseHandler.hpv"
};   //CloseHandler


/*----------------------------------------------------------------------------*/
/* Resume compiler default packing.                                           */
/*----------------------------------------------------------------------------*/
#pragma pack()

#endif
