/*******************************************************************************
* FILE NAME: Confirmation.cpp                                                  *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Class implementation of the class:                                         *
*     Confirmation- Confirmation message box                                   *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _INOTIFEV_
#include <inotifev.hpp>
#endif

#ifndef _IOBSERVR_
#include <iobservr.hpp>
#endif

#ifndef _ISTDNTFY_
#include <istdntfy.hpp>
#endif

#ifndef _CONFIRMATION_
#include "Confirmation.hpp"
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef _ITRACE_
#include <itrace.hpp>
#endif


#pragma export (Confirmation::readyId)
const INotificationId Confirmation::readyId = "Confirmation::readyId";

//------------------------------------------------------------------------------
// Confirmation :: Confirmation
//------------------------------------------------------------------------------
#pragma export (Confirmation::Confirmation())
Confirmation::Confirmation()
{

   construct();
}     //end constructor


//------------------------------------------------------------------------------
// Confirmation :: ~Confirmation
//------------------------------------------------------------------------------
#pragma export (Confirmation::~Confirmation())
Confirmation::~Confirmation()
{

}

//------------------------------------------------------------------------------
// Confirmation :: initializePart
//------------------------------------------------------------------------------
#pragma export (Confirmation::initializePart())
Confirmation & Confirmation::initializePart()
{
   makeConnections();
   notifyObservers(INotificationEvent(readyId, *this));
   return *this;
}


//------------------------------------------------------------------------------
// Confirmation :: makeConnections
//------------------------------------------------------------------------------
#pragma export (Confirmation::makeConnections())
Boolean Confirmation::makeConnections()
{
   this->enableNotification();

   return true;
}


#include "Confirmation.cpv"
