/*******************************************************************************
* FILE NAME: VyDocProperties.hpp                                               *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Declaration of the class:                                                  *
*     VyDocProperties- Properties dialog for Vyper document                    *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _VYDOCPROPERTIES_
#define _VYDOCPROPERTIES_  

class VyDocProperties;

#ifndef _IFRAME_
#include <iframe.hpp>
#endif

#ifndef _IOBSERVR_
#include <iobservr.hpp>
#endif

class ISetCanvas;
class IStaticText;
class IEntryField;
class IPushButton;
#ifndef _IVBVPRTP_
#include <ivbvprtp.h>
#endif

#ifndef _VYDOC_
#include "VyDoc.hpp"
#endif

#ifndef _IRECT_
#include <irect.hpp>
#endif

#ifndef _ISTRING_
#include <istring.hpp>
#endif

class VyDocPropertiesConn0;
class VyDocPropertiesConn1;
class VyDocPropertiesConn2;
class VyDocPropertiesConn3;
class VyDocPropertiesConn4;
class VyDocPropertiesConn5;
#include "VyDocProperties.h"


/*----------------------------------------------------------------------------*/
/* Align classes on four byte boundary.                                       */
/*----------------------------------------------------------------------------*/
#pragma pack(4)

//*****************************************************************************
// Class definition for VyDocProperties
//*****************************************************************************
class VyDocProperties : public IFrameWindow, public IObserver {
public:
   //---------------------------------------------------------------------------
   // Constructors / destructors
   //---------------------------------------------------------------------------
   VyDocProperties(
      unsigned long id = WND_VyDocProperties,
      IWindow* parent = IWindow::desktopWindow(),
      IWindow* owner = 0,
      const IRectangle& rect = defaultFramingSpec(),
      const IFrameWindow::Style& style = defaultStyle(),
      const char* title = defaultTitle());

   virtual  ~VyDocProperties();

   //---------------------------------------------------------------------------
   // public member functions
   //---------------------------------------------------------------------------
   static const IRectangle defaultFramingSpec();
   static const IFrameWindow::Style defaultStyle();
   static IString defaultTitle();
   virtual VyDocProperties & initializePart();
   VyDocProperties * getFrameWindow() { return this; };
   IVBVariablePartPointer<VyDoc *> *  getDocument() const { return iDocument; };

   //---------------------------------------------------------------------------
   // public member data
   //---------------------------------------------------------------------------
   static const INotificationId readyId;
   static const INotificationId document;

protected:
   //---------------------------------------------------------------------------
   // protected member functions
   //---------------------------------------------------------------------------
   Boolean makeConnections();
   virtual IObserver & dispatchNotificationEvent(const INotificationEvent & anEvent);

private:
   //---------------------------------------------------------------------------
   // private member data
   //---------------------------------------------------------------------------
   ISetCanvas * iSetCanvas1;
   IStaticText * iTitleLabel;
   IEntryField * iTitle;
   IStaticText * iSubjectLabel;
   IEntryField * iSubject;
   IStaticText * iVersionLabel;
   IEntryField * iVersion;
   IStaticText * iCopyrightLabel;
   IEntryField * iCopyright;
   IStaticText * iAuthorLabel;
   IEntryField * iAuthor;
   IPushButton * iClose;
   IVBVariablePartPointer<VyDoc *> * iDocument;
   VyDocPropertiesConn0 * conn0;
   VyDocPropertiesConn1 * conn1;
   VyDocPropertiesConn2 * conn2;
   VyDocPropertiesConn3 * conn3;
   VyDocPropertiesConn4 * conn4;
   VyDocPropertiesConn5 * conn5;


};   //VyDocProperties


/*----------------------------------------------------------------------------*/
/* Resume compiler default packing.                                           */
/*----------------------------------------------------------------------------*/
#pragma pack()

#endif
