/*******************************************************************************
* FILE NAME: VyDoc.cpp                                                         *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Class implementation of the class:                                         *
*     VyDoc- Represents a VYD file                                             *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _INOTIFEV_
#include <inotifev.hpp>
#endif

#ifndef _IOBSERVR_
#include <iobservr.hpp>
#endif

#ifndef _ISTDNTFY_
#include <istdntfy.hpp>
#endif

#ifndef _VYDOC_
#include "VyDoc.hpp"
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef _ITRACE_
#include <itrace.hpp>
#endif


#pragma export (VyDoc::readyId)
const INotificationId VyDoc::readyId = "VyDoc::readyId";

#pragma export (VyDoc::sections)
const INotificationId VyDoc::sections = "VyDoc::sections";

#pragma export (VyDoc::arts)
const INotificationId VyDoc::arts = "VyDoc::arts";

//------------------------------------------------------------------------------
// VyDoc :: VyDoc
//------------------------------------------------------------------------------
#pragma export (VyDoc::VyDoc())
VyDoc::VyDoc()
{
   iSections = new IVSequence< VySection* >();
   iArts = new IVSequence< VyArt* >();

   construct();
}     //end constructor


//------------------------------------------------------------------------------
// VyDoc :: ~VyDoc
//------------------------------------------------------------------------------
#pragma export (VyDoc::~VyDoc())
VyDoc::~VyDoc()
{
   destruct();
   this->stopHandlingNotificationsFor(*iSections);
   this->stopHandlingNotificationsFor(*iArts);

   delete iSections;
   delete iArts;
}

//------------------------------------------------------------------------------
// VyDoc :: initializePart
//------------------------------------------------------------------------------
#pragma export (VyDoc::initializePart())
VyDoc & VyDoc::initializePart()
{
   this->handleNotificationsFor(*iSections);
   this->handleNotificationsFor(*iArts);
   makeConnections();
   notifyObservers(INotificationEvent(readyId, *this));
   return *this;
}


//------------------------------------------------------------------------------
// VyDoc :: makeConnections
//------------------------------------------------------------------------------
#pragma export (VyDoc::makeConnections())
Boolean VyDoc::makeConnections()
{
   this->enableNotification();
   iSections->enableNotification();
   iArts->enableNotification();

   return true;
}


//------------------------------------------------------------------------------
// VyDoc :: dispatchNotificationEvent
//------------------------------------------------------------------------------
#pragma export (VyDoc::dispatchNotificationEvent(const INotificationEvent &))
IObserver & VyDoc::dispatchNotificationEvent(const INotificationEvent & anEvent)
{


   return *this;
}



#include "VyDoc.cpv"
