/*******************************************************************************
* FILE NAME: VyDocProperties.h                                                 *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Constant declarations for class:                                           *
*     VyDocProperties- Properties dialog for Vyper document                    *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _ICCONST_
#include <icconst.h>
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef WND_VyDocProperties
#define WND_VyDocProperties  VBBASEWINDOWID
#endif

#define WNDOFFSET_VyDocProperties_FrameWindow  0
#define WND_VyDocProperties_FrameWindow  WND_VyDocProperties

#define WND_VyDocProperties_SetCanvas1  IC_FRAME_CLIENT_ID

#define WNDOFFSET_VyDocProperties_TitleLabel  1
#define WND_VyDocProperties_TitleLabel  WND_VyDocProperties + WNDOFFSET_VyDocProperties_TitleLabel

#define WNDOFFSET_VyDocProperties_Title  2
#define WND_VyDocProperties_Title  WND_VyDocProperties + WNDOFFSET_VyDocProperties_Title

#define WNDOFFSET_VyDocProperties_SubjectLabel  3
#define WND_VyDocProperties_SubjectLabel  WND_VyDocProperties + WNDOFFSET_VyDocProperties_SubjectLabel

#define WNDOFFSET_VyDocProperties_Subject  4
#define WND_VyDocProperties_Subject  WND_VyDocProperties + WNDOFFSET_VyDocProperties_Subject

#define WNDOFFSET_VyDocProperties_VersionLabel  5
#define WND_VyDocProperties_VersionLabel  WND_VyDocProperties + WNDOFFSET_VyDocProperties_VersionLabel

#define WNDOFFSET_VyDocProperties_Version  6
#define WND_VyDocProperties_Version  WND_VyDocProperties + WNDOFFSET_VyDocProperties_Version

#define WNDOFFSET_VyDocProperties_CopyrightLabel  7
#define WND_VyDocProperties_CopyrightLabel  WND_VyDocProperties + WNDOFFSET_VyDocProperties_CopyrightLabel

#define WNDOFFSET_VyDocProperties_Copyright  8
#define WND_VyDocProperties_Copyright  WND_VyDocProperties + WNDOFFSET_VyDocProperties_Copyright

#define WNDOFFSET_VyDocProperties_AuthorLabel  9
#define WND_VyDocProperties_AuthorLabel  WND_VyDocProperties + WNDOFFSET_VyDocProperties_AuthorLabel

#define WNDOFFSET_VyDocProperties_Author  10
#define WND_VyDocProperties_Author  WND_VyDocProperties + WNDOFFSET_VyDocProperties_Author

#define WNDOFFSET_VyDocProperties_Close  11
#define WND_VyDocProperties_Close  WND_VyDocProperties + WNDOFFSET_VyDocProperties_Close



