/*******************************************************************************
* FILE NAME: VyFont.cpp                                                        *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Class implementation of the class:                                         *
*     VyFont- Font wrapper                                                     *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _INOTIFEV_
#include <inotifev.hpp>
#endif

#ifndef _IOBSERVR_
#include <iobservr.hpp>
#endif

#ifndef _ISTDNTFY_
#include <istdntfy.hpp>
#endif

#ifndef _VYFONT_
#include "VyFont.hpp"
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef _ITRACE_
#include <itrace.hpp>
#endif


#pragma export (VyFont::readyId)
const INotificationId VyFont::readyId = "VyFont::readyId";

//------------------------------------------------------------------------------
// VyFont :: VyFont
//------------------------------------------------------------------------------
#pragma export (VyFont::VyFont())
VyFont::VyFont()
{

   construct();
}     //end constructor


//------------------------------------------------------------------------------
// VyFont :: ~VyFont
//------------------------------------------------------------------------------
#pragma export (VyFont::~VyFont())
VyFont::~VyFont()
{

}

//------------------------------------------------------------------------------
// VyFont :: initializePart
//------------------------------------------------------------------------------
#pragma export (VyFont::initializePart())
VyFont & VyFont::initializePart()
{
   makeConnections();
   notifyObservers(INotificationEvent(readyId, *this));
   return *this;
}


//------------------------------------------------------------------------------
// VyFont :: makeConnections
//------------------------------------------------------------------------------
#pragma export (VyFont::makeConnections())
Boolean VyFont::makeConnections()
{
   this->enableNotification();

   return true;
}


#include "VyFont.cpv"
