/*******************************************************************************
* FILE NAME: VyInfo.h                                                          *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Constant declarations for class:                                           *
*     VyInfo- Product info screen                                              *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _ICCONST_
#include <icconst.h>
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef WND_VyInfo
#define WND_VyInfo  VBBASEWINDOWID
#endif

#define WNDOFFSET_VyInfo_FrameWindow  0
#define WND_VyInfo_FrameWindow  WND_VyInfo

#define WND_VyInfo_SetCanvas1  IC_FRAME_CLIENT_ID

#define WNDOFFSET_VyInfo_BitmapControl1  1
#define WND_VyInfo_BitmapControl1  WND_VyInfo + WNDOFFSET_VyInfo_BitmapControl1

#define WNDOFFSET_VyInfo_MultiCellCanvas1  2
#define WND_VyInfo_MultiCellCanvas1  WND_VyInfo + WNDOFFSET_VyInfo_MultiCellCanvas1

#define WNDOFFSET_VyInfo_Logo  3
#define WND_VyInfo_Logo  WND_VyInfo + WNDOFFSET_VyInfo_Logo

#define WNDOFFSET_VyInfo_VyperVersion  4
#define WND_VyInfo_VyperVersion  WND_VyInfo + WNDOFFSET_VyInfo_VyperVersion

#define WNDOFFSET_VyInfo_VyGen  5
#define WND_VyInfo_VyGen  WND_VyInfo + WNDOFFSET_VyInfo_VyGen

#define WNDOFFSET_VyInfo_GeneratorVersion  6
#define WND_VyInfo_GeneratorVersion  WND_VyInfo + WNDOFFSET_VyInfo_GeneratorVersion

#define WNDOFFSET_VyInfo_VyDit  7
#define WND_VyInfo_VyDit  WND_VyInfo + WNDOFFSET_VyInfo_VyDit

#define WNDOFFSET_VyInfo_EditorVersion  8
#define WND_VyInfo_EditorVersion  WND_VyInfo + WNDOFFSET_VyInfo_EditorVersion

#define WNDOFFSET_VyInfo_Copyright  9
#define WND_VyInfo_Copyright  WND_VyInfo + WNDOFFSET_VyInfo_Copyright

#define WNDOFFSET_VyInfo_Contents  10
#define WND_VyInfo_Contents  WND_VyInfo + WNDOFFSET_VyInfo_Contents

#define WNDOFFSET_VyInfo_Registration  11
#define WND_VyInfo_Registration  WND_VyInfo + WNDOFFSET_VyInfo_Registration


