/*******************************************************************************
* FILE NAME: VyInfo.hpp                                                        *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Declaration of the class:                                                  *
*     VyInfo- Product info screen                                              *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _VYINFO_
#define _VYINFO_  

class VyInfo;

#ifndef _IFRAME_
#include <iframe.hpp>
#endif

#ifndef _IOBSERVR_
#include <iobservr.hpp>
#endif

class ISetCanvas;
class IBitmapControl;
class IMultiCellCanvas;
class IStaticText;
#ifndef _IPUSHBUT_
#include <ipushbut.hpp>
#endif

#ifndef _IRECT_
#include <irect.hpp>
#endif

#ifndef _ISTRING_
#include <istring.hpp>
#endif

#ifndef GENERATOR_HPP
#include "Generator.hpp"
#endif

#ifndef EDITOR_HPP
#include "Editor.hpp"
#endif

class VyInfoConn0;
class VyInfoConn1;
class VyInfoConn2;
#include "VyInfo.h"


/*----------------------------------------------------------------------------*/
/* Align classes on four byte boundary.                                       */
/*----------------------------------------------------------------------------*/
#pragma pack(4)

//*****************************************************************************
// Class definition for VyInfo
//*****************************************************************************
class VyInfo : public IFrameWindow, public IObserver {
public:
   //---------------------------------------------------------------------------
   // Constructors / destructors
   //---------------------------------------------------------------------------
   VyInfo(
      unsigned long id = WND_VyInfo,
      IWindow* parent = IWindow::desktopWindow(),
      IWindow* owner = 0,
      const IRectangle& rect = defaultFramingSpec(),
      const IFrameWindow::Style& style = defaultStyle(),
      const char* title = defaultTitle());

   virtual  ~VyInfo();

   //---------------------------------------------------------------------------
   // public member functions
   //---------------------------------------------------------------------------
   static const IRectangle defaultFramingSpec();
   static const IFrameWindow::Style defaultStyle();
   static IString defaultTitle();
   virtual VyInfo & initializePart();
   VyInfo * getFrameWindow() { return this; };
   IPushButton *  getContents() const { return iContents; };

   //---------------------------------------------------------------------------
   // public member data
   //---------------------------------------------------------------------------
   static const INotificationId readyId;
   static const INotificationId contentsButtonClickEvent;

protected:
   //---------------------------------------------------------------------------
   // protected member functions
   //---------------------------------------------------------------------------
   Boolean makeConnections();
   virtual IObserver & dispatchNotificationEvent(const INotificationEvent & anEvent);

private:
   //---------------------------------------------------------------------------
   // private member data
   //---------------------------------------------------------------------------
   ISetCanvas * iSetCanvas1;
   IBitmapControl * iBitmapControl1;
   IMultiCellCanvas * iMultiCellCanvas1;
   IStaticText * iLogo;
   IStaticText * iVyperVersion;
   IStaticText * iVyGen;
   IStaticText * iGeneratorVersion;
   IStaticText * iVyDit;
   IStaticText * iEditorVersion;
   IStaticText * iCopyright;
   IPushButton * iContents;
   IStaticText * iRegistration;
   VyInfoConn0 * conn0;
   VyInfoConn1 * conn1;
   VyInfoConn2 * conn2;

friend class VyInfoConn0;
friend class VyInfoConn1;
friend class VyInfoConn2;

#include "VyInfo.hpv"
};   //VyInfo


/*----------------------------------------------------------------------------*/
/* Resume compiler default packing.                                           */
/*----------------------------------------------------------------------------*/
#pragma pack()

#endif
