/*******************************************************************************
* FILE NAME: VyKeyword.h                                                       *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Constant declarations for class:                                           *
*     VyKeyword- Keyword or index entry (adapts KeywordGin)                    *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _ICCONST_
#include <icconst.h>
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef WND_VyKeyword
#define WND_VyKeyword  VBBASEWINDOWID
#endif


