/*******************************************************************************
* FILE NAME: VyKeywordProperties.h                                             *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Constant declarations for class:                                           *
*     VyKeywordProperties- Dialog for editing keywords                         *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _ICCONST_
#include <icconst.h>
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef WND_VyKeywordProperties
#define WND_VyKeywordProperties  VBBASEWINDOWID
#endif

#define WNDOFFSET_VyKeywordProperties_FrameWindow  0
#define WND_VyKeywordProperties_FrameWindow  WND_VyKeywordProperties

#define WND_VyKeywordProperties_MultiCellCanvas1  IC_FRAME_CLIENT_ID

#define WNDOFFSET_VyKeywordProperties_NameLabel  1
#define WND_VyKeywordProperties_NameLabel  WND_VyKeywordProperties + WNDOFFSET_VyKeywordProperties_NameLabel

#define WNDOFFSET_VyKeywordProperties_Name  2
#define WND_VyKeywordProperties_Name  WND_VyKeywordProperties + WNDOFFSET_VyKeywordProperties_Name

#define WNDOFFSET_VyKeywordProperties_Index  3
#define WND_VyKeywordProperties_Index  WND_VyKeywordProperties + WNDOFFSET_VyKeywordProperties_Index

#define WNDOFFSET_VyKeywordProperties_Global  4
#define WND_VyKeywordProperties_Global  WND_VyKeywordProperties + WNDOFFSET_VyKeywordProperties_Global

#define WNDOFFSET_VyKeywordProperties_Close  5
#define WND_VyKeywordProperties_Close  WND_VyKeywordProperties + WNDOFFSET_VyKeywordProperties_Close



