/*******************************************************************************
* FILE NAME: VyLabel.cpp                                                       *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Class implementation of the class:                                         *
*     VyLabel- hypertext label/anchor (adapts LabelGin)                        *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _INOTIFEV_
#include <inotifev.hpp>
#endif

#ifndef _IOBSERVR_
#include <iobservr.hpp>
#endif

#ifndef _ISTDNTFY_
#include <istdntfy.hpp>
#endif

#ifndef _VYLABEL_
#include "VyLabel.hpp"
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef _ITRACE_
#include <itrace.hpp>
#endif


#pragma export (VyLabel::readyId)
const INotificationId VyLabel::readyId = "VyLabel::readyId";

//------------------------------------------------------------------------------
// VyLabel :: VyLabel
//------------------------------------------------------------------------------
#pragma export (VyLabel::VyLabel())
VyLabel::VyLabel()
{

   construct();
}     //end constructor


//------------------------------------------------------------------------------
// VyLabel :: ~VyLabel
//------------------------------------------------------------------------------
#pragma export (VyLabel::~VyLabel())
VyLabel::~VyLabel()
{

}

//------------------------------------------------------------------------------
// VyLabel :: initializePart
//------------------------------------------------------------------------------
#pragma export (VyLabel::initializePart())
VyLabel & VyLabel::initializePart()
{
   makeConnections();
   notifyObservers(INotificationEvent(readyId, *this));
   return *this;
}


//------------------------------------------------------------------------------
// VyLabel :: makeConnections
//------------------------------------------------------------------------------
#pragma export (VyLabel::makeConnections())
Boolean VyLabel::makeConnections()
{
   this->enableNotification();

   return true;
}


#include "VyLabel.cpv"
