/*******************************************************************************
* FILE NAME: VyLinkProperties.hpp                                              *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Declaration of the class:                                                  *
*     VyLinkProperties- Dialog for editing links                               *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _VYLINKPROPERTIES_
#define _VYLINKPROPERTIES_  

class VyLinkProperties;

#ifndef _IFRAME_
#include <iframe.hpp>
#endif

#ifndef _IOBSERVR_
#include <iobservr.hpp>
#endif

class IMultiCellCanvas;
class IStaticText;
class IComboBox;
class ICheckBox;
class IEntryField;
class IPushButton;
#ifndef _VYLINK_
#include "VyLink.hpp"
#endif

#ifndef _IVBVPRTP_
#include <ivbvprtp.h>
#endif

#ifndef _VYDOC_
#include "VyDoc.hpp"
#endif

class ExceptionNotification;
#ifndef _IRECT_
#include <irect.hpp>
#endif

#ifndef _ISTRING_
#include <istring.hpp>
#endif

class VyLinkPropertiesConn0;
class VyLinkPropertiesConn1;
class VyLinkPropertiesConn2;
class VyLinkPropertiesConn3;
class VyLinkPropertiesConn5;
class VyLinkPropertiesConn7;
class VyLinkPropertiesConn6;
class VyLinkPropertiesConn18;
class VyLinkPropertiesConn9;
class VyLinkPropertiesConn10;
class VyLinkPropertiesConn11;
class VyLinkPropertiesConn12;
#include "VyLinkProperties.h"


/*----------------------------------------------------------------------------*/
/* Align classes on four byte boundary.                                       */
/*----------------------------------------------------------------------------*/
#pragma pack(4)

//*****************************************************************************
// Class definition for VyLinkProperties
//*****************************************************************************
class VyLinkProperties : public IFrameWindow, public IObserver {
public:
   //---------------------------------------------------------------------------
   // Constructors / destructors
   //---------------------------------------------------------------------------
   VyLinkProperties(
      unsigned long id = WND_VyLinkProperties,
      IWindow* parent = IWindow::desktopWindow(),
      IWindow* owner = 0,
      const IRectangle& rect = defaultFramingSpec(),
      const IFrameWindow::Style& style = defaultStyle(),
      const char* title = defaultTitle());

   virtual  ~VyLinkProperties();

   //---------------------------------------------------------------------------
   // public member functions
   //---------------------------------------------------------------------------
   static const IRectangle defaultFramingSpec();
   static const IFrameWindow::Style defaultStyle();
   static IString defaultTitle();
   virtual VyLinkProperties & initializePart();
   VyLinkProperties * getFrameWindow() { return this; };
   VyLink *  getLink() const { return iLink; };
   IVBVariablePartPointer<VyDoc *> *  getDocument() const { return iDocument; };

   //---------------------------------------------------------------------------
   // public member data
   //---------------------------------------------------------------------------
   static const INotificationId readyId;
   static const INotificationId linkGin;
   static const INotificationId document;

protected:
   //---------------------------------------------------------------------------
   // protected member functions
   //---------------------------------------------------------------------------
   Boolean makeConnections();
   virtual IObserver & dispatchNotificationEvent(const INotificationEvent & anEvent);

private:
   //---------------------------------------------------------------------------
   // private member data
   //---------------------------------------------------------------------------
   IMultiCellCanvas * iMultiCellCanvas1;
   IStaticText * iTargetLabel;
   IComboBox * iTarget;
   ICheckBox * iExternal;
   IEntryField * iFile;
   IPushButton * iClose;
   VyLink * iLink;
   IVBVariablePartPointer<VyDoc *> * iDocument;
   ExceptionNotification * iExceptionNotification;
   VyLinkPropertiesConn0 * conn0;
   VyLinkPropertiesConn1 * conn1;
   VyLinkPropertiesConn2 * conn2;
   VyLinkPropertiesConn3 * conn3;
   VyLinkPropertiesConn5 * conn5;
   VyLinkPropertiesConn7 * conn7;
   VyLinkPropertiesConn6 * conn6;
   VyLinkPropertiesConn18 * conn18;
   VyLinkPropertiesConn9 * conn9;
   VyLinkPropertiesConn10 * conn10;
   VyLinkPropertiesConn11 * conn11;
   VyLinkPropertiesConn12 * conn12;


#include "VyLinkProperties.hpv"
};   //VyLinkProperties


/*----------------------------------------------------------------------------*/
/* Resume compiler default packing.                                           */
/*----------------------------------------------------------------------------*/
#pragma pack()

#endif
