/*******************************************************************************
* FILE NAME: VyLink.cpp                                                        *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Class implementation of the class:                                         *
*     VyLink- Link attribute                                                   *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _INOTIFEV_
#include <inotifev.hpp>
#endif

#ifndef _IOBSERVR_
#include <iobservr.hpp>
#endif

#ifndef _ISTDNTFY_
#include <istdntfy.hpp>
#endif

#ifndef _VYLINK_
#include "VyLink.hpp"
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef _ITRACE_
#include <itrace.hpp>
#endif


#pragma export (VyLink::readyId)
const INotificationId VyLink::readyId = "VyLink::readyId";

//------------------------------------------------------------------------------
// VyLink :: VyLink
//------------------------------------------------------------------------------
#pragma export (VyLink::VyLink())
VyLink::VyLink()
{

   construct();
}     //end constructor


//------------------------------------------------------------------------------
// VyLink :: ~VyLink
//------------------------------------------------------------------------------
#pragma export (VyLink::~VyLink())
VyLink::~VyLink()
{

}

//------------------------------------------------------------------------------
// VyLink :: initializePart
//------------------------------------------------------------------------------
#pragma export (VyLink::initializePart())
VyLink & VyLink::initializePart()
{
   makeConnections();
   notifyObservers(INotificationEvent(readyId, *this));
   return *this;
}


//------------------------------------------------------------------------------
// VyLink :: makeConnections
//------------------------------------------------------------------------------
#pragma export (VyLink::makeConnections())
Boolean VyLink::makeConnections()
{
   this->enableNotification();

   return true;
}


#include "VyLink.cpv"
