/*******************************************************************************
* FILE NAME: VyRegistration.h                                                  *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Constant declarations for class:                                           *
*     VyRegistration- Registration dialog                                      *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _ICCONST_
#include <icconst.h>
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef WND_VyRegistration
#define WND_VyRegistration  VBBASEWINDOWID
#endif

#define WNDOFFSET_VyRegistration_FrameWindow  0
#define WND_VyRegistration_FrameWindow  WND_VyRegistration

#define WND_VyRegistration_MultiCellCanvas1  IC_FRAME_CLIENT_ID

#define WNDOFFSET_VyRegistration_UserLabel  1
#define WND_VyRegistration_UserLabel  WND_VyRegistration + WNDOFFSET_VyRegistration_UserLabel

#define WNDOFFSET_VyRegistration_User  2
#define WND_VyRegistration_User  WND_VyRegistration + WNDOFFSET_VyRegistration_User

#define WNDOFFSET_VyRegistration_KeyLabel  3
#define WND_VyRegistration_KeyLabel  WND_VyRegistration + WNDOFFSET_VyRegistration_KeyLabel

#define WNDOFFSET_VyRegistration_Key  4
#define WND_VyRegistration_Key  WND_VyRegistration + WNDOFFSET_VyRegistration_Key

#define WNDOFFSET_VyRegistration_Notice  5
#define WND_VyRegistration_Notice  WND_VyRegistration + WNDOFFSET_VyRegistration_Notice

#define WNDOFFSET_VyRegistration_Register  6
#define WND_VyRegistration_Register  WND_VyRegistration + WNDOFFSET_VyRegistration_Register

#define WNDOFFSET_VyRegistration_Cancel  7
#define WND_VyRegistration_Cancel  WND_VyRegistration + WNDOFFSET_VyRegistration_Cancel



