/*******************************************************************************
* FILE NAME: VyRegistration.hpp                                                *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Declaration of the class:                                                  *
*     VyRegistration- Registration dialog                                      *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _VYREGISTRATION_
#define _VYREGISTRATION_  

class VyRegistration;

#ifndef _IFRAME_
#include <iframe.hpp>
#endif

class IMultiCellCanvas;
class IStaticText;
class IEntryField;
class IPushButton;
class ExceptionNotification;
#ifndef _IRECT_
#include <irect.hpp>
#endif

#ifndef _ISTRING_
#include <istring.hpp>
#endif

#ifndef GENERATOR_HPP
#include "Generator.hpp"
#endif

class VyRegistrationConn0;
class VyRegistrationConn1;
class VyRegistrationConn4;
class VyRegistrationConn5;
#include "VyRegistration.h"


/*----------------------------------------------------------------------------*/
/* Align classes on four byte boundary.                                       */
/*----------------------------------------------------------------------------*/
#pragma pack(4)

//*****************************************************************************
// Class definition for VyRegistration
//*****************************************************************************
class VyRegistration : public IFrameWindow {
public:
   //---------------------------------------------------------------------------
   // Constructors / destructors
   //---------------------------------------------------------------------------
   VyRegistration(
      unsigned long id = WND_VyRegistration,
      IWindow* parent = IWindow::desktopWindow(),
      IWindow* owner = 0,
      const IRectangle& rect = defaultFramingSpec(),
      const IFrameWindow::Style& style = defaultStyle(),
      const char* title = defaultTitle());

   virtual  ~VyRegistration();

   //---------------------------------------------------------------------------
   // public member functions
   //---------------------------------------------------------------------------
   static const IRectangle defaultFramingSpec();
   static const IFrameWindow::Style defaultStyle();
   static IString defaultTitle();
   virtual VyRegistration & initializePart();
   VyRegistration * getFrameWindow() { return this; };

   //---------------------------------------------------------------------------
   // public member data
   //---------------------------------------------------------------------------
   static const INotificationId readyId;

protected:
   //---------------------------------------------------------------------------
   // protected member functions
   //---------------------------------------------------------------------------
   Boolean makeConnections();

private:
   //---------------------------------------------------------------------------
   // private member data
   //---------------------------------------------------------------------------
   IMultiCellCanvas * iMultiCellCanvas1;
   IStaticText * iUserLabel;
   IEntryField * iUser;
   IStaticText * iKeyLabel;
   IEntryField * iKey;
   IStaticText * iNotice;
   IPushButton * iRegister;
   IPushButton * iCancel;
   ExceptionNotification * iExceptionNotification;
   VyRegistrationConn0 * conn0;
   VyRegistrationConn1 * conn1;
   VyRegistrationConn4 * conn4;
   VyRegistrationConn5 * conn5;


#include "VyRegistration.hpv"
};   //VyRegistration


/*----------------------------------------------------------------------------*/
/* Resume compiler default packing.                                           */
/*----------------------------------------------------------------------------*/
#pragma pack()

#endif
