/*******************************************************************************
* FILE NAME: VySectionProperties.hpp                                           *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Declaration of the class:                                                  *
*     VySectionProperties                                                      *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _VYSECTIONPROPERTIES_
#define _VYSECTIONPROPERTIES_  

class VySectionProperties;

#ifndef _IFRAME_
#include <iframe.hpp>
#endif

#ifndef _IOBSERVR_
#include <iobservr.hpp>
#endif

class IMultiCellCanvas;
class IStaticText;
class IEntryField;
class ICheckBox;
#define INCL_WINSTDCNR
#include <os2.h>

#ifndef _VYKEYWORD_
#include "VyKeyword.hpp"
#endif

#ifndef _IVSEQ_H_
#include <ivseq.h>
#endif

#ifndef _IVBCNR_
#include <ivbcnr.h>
#endif

class IContainerColumn;
class ISetCanvas;
class IPushButton;
#ifndef _VYLABEL_
#include "VyLabel.hpp"
#endif

#ifndef _IVBVPRTP_
#include <ivbvprtp.h>
#endif

#ifndef _VYSECTION_
#include "VySection.hpp"
#endif

class VyLabel;
#ifndef _ISTDNTFY_
#include <istdntfy.hpp>
#endif

class VyKeywordProperties;
class VyKeyword;
class VyLabelProperties;
class ExceptionNotification;
#ifndef _IRECT_
#include <irect.hpp>
#endif

#ifndef _ISTRING_
#include <istring.hpp>
#endif

class VySectionPropertiesConn0;
class VySectionPropertiesConn1;
class VySectionPropertiesConn2;
class VySectionPropertiesConn3;
class VySectionPropertiesConn4;
class VySectionPropertiesConn5;
class VySectionPropertiesConn7;
class VySectionPropertiesConn8;
class VySectionPropertiesConn9;
class VySectionPropertiesConn10;
class VySectionPropertiesConn11;
class VySectionPropertiesConn12;
class VySectionPropertiesConn27;
class VySectionPropertiesConn14;
class VySectionPropertiesConn15;
class VySectionPropertiesConn16;
class VySectionPropertiesConn17;
class VySectionPropertiesConn18;
class VySectionPropertiesConn19;
class VySectionPropertiesConn20;
class VySectionPropertiesConn21;
class VySectionPropertiesConn24;
class VySectionPropertiesConn26;
class VySectionPropertiesConn29;
class VySectionPropertiesConn23;
class VySectionPropertiesConn31;
class VySectionPropertiesConn32;
class VySectionPropertiesConn33;
class VySectionPropertiesConn34;
class VySectionPropertiesConn35;
class VySectionPropertiesConn36;
class VySectionPropertiesConn37;
class VySectionPropertiesConn38;
class VySectionPropertiesConn39;
class VySectionPropertiesConn40;
class VySectionPropertiesConn41;
class VySectionPropertiesConn42;
class VySectionPropertiesConn43;
class VySectionPropertiesConn44;
class VySectionPropertiesConn45;
class VySectionPropertiesConn46;
#include "VySectionProperties.h"


/*----------------------------------------------------------------------------*/
/* Align classes on four byte boundary.                                       */
/*----------------------------------------------------------------------------*/
#pragma pack(4)

//*****************************************************************************
// Class definition for VySectionPropertiesKeywordContainerCnrObj
//*****************************************************************************
class VySectionPropertiesKeywordContainerCnrObj : public IVBContainerObject {
public:
   //---------------------------------------------------------------------------
   // Constructors / destructors
   //---------------------------------------------------------------------------
   VySectionPropertiesKeywordContainerCnrObj(VyKeyword& anObject);
   VySectionPropertiesKeywordContainerCnrObj(VySectionPropertiesKeywordContainerCnrObj& anObject);

   virtual  ~VySectionPropertiesKeywordContainerCnrObj();

   //---------------------------------------------------------------------------
   // public member functions
   //---------------------------------------------------------------------------
   IVBContainerObject & refreshFromObject();
   IVBContainerObject & updateToObject();
   VySectionPropertiesKeywordContainerCnrObj& operator=(const VySectionPropertiesKeywordContainerCnrObj& anObject);
   VyKeyword* realObject() { return &pRealObject; }
;

   //---------------------------------------------------------------------------
   // public member data
   //---------------------------------------------------------------------------
   IString ilistedString;
   IString iexternalString;

protected:
private:
   //---------------------------------------------------------------------------
   // private member data
   //---------------------------------------------------------------------------
   VyKeyword & pRealObject;


};   //VySectionPropertiesKeywordContainerCnrObj


//*****************************************************************************
// Class definition for VySectionPropertiesLabelContainerCnrObj
//*****************************************************************************
class VySectionPropertiesLabelContainerCnrObj : public IVBContainerObject {
public:
   //---------------------------------------------------------------------------
   // Constructors / destructors
   //---------------------------------------------------------------------------
   VySectionPropertiesLabelContainerCnrObj(VyLabel& anObject);
   VySectionPropertiesLabelContainerCnrObj(VySectionPropertiesLabelContainerCnrObj& anObject);

   virtual  ~VySectionPropertiesLabelContainerCnrObj();

   //---------------------------------------------------------------------------
   // public member functions
   //---------------------------------------------------------------------------
   IVBContainerObject & refreshFromObject();
   IVBContainerObject & updateToObject();
   VySectionPropertiesLabelContainerCnrObj& operator=(const VySectionPropertiesLabelContainerCnrObj& anObject);
   VyLabel* realObject() { return &pRealObject; }
;

   //---------------------------------------------------------------------------
   // public member data
   //---------------------------------------------------------------------------
   IString iidString;
   IString iexternalString;

protected:
private:
   //---------------------------------------------------------------------------
   // private member data
   //---------------------------------------------------------------------------
   VyLabel & pRealObject;


};   //VySectionPropertiesLabelContainerCnrObj


//*****************************************************************************
// Class definition for VySectionPropertiesLabelFactoryFactory
//*****************************************************************************
class VySectionPropertiesLabelFactoryFactory : public IStandardNotifier {
public:
   //---------------------------------------------------------------------------
   // Constructors / destructors
   //---------------------------------------------------------------------------
   VySectionPropertiesLabelFactoryFactory();

   virtual  ~VySectionPropertiesLabelFactoryFactory();

   //---------------------------------------------------------------------------
   // public member functions
   //---------------------------------------------------------------------------
   VyLabel * create();

   //---------------------------------------------------------------------------
   // public member data
   //---------------------------------------------------------------------------
   static const INotificationId newObjectCreatedId;

protected:
private:

};   //VySectionPropertiesLabelFactoryFactory


//*****************************************************************************
// Class definition for VySectionPropertiesKeywordPropertiesFactoryFactory
//*****************************************************************************
class VySectionPropertiesKeywordPropertiesFactoryFactory : public IStandardNotifier {
public:
   //---------------------------------------------------------------------------
   // Constructors / destructors
   //---------------------------------------------------------------------------
   VySectionPropertiesKeywordPropertiesFactoryFactory(unsigned long anId);

   virtual  ~VySectionPropertiesKeywordPropertiesFactoryFactory();

   //---------------------------------------------------------------------------
   // public member functions
   //---------------------------------------------------------------------------
   VyKeywordProperties * create();

   //---------------------------------------------------------------------------
   // public member data
   //---------------------------------------------------------------------------
   static const INotificationId newObjectCreatedId;

protected:
private:
   //---------------------------------------------------------------------------
   // private member data
   //---------------------------------------------------------------------------
   static unsigned long id;


};   //VySectionPropertiesKeywordPropertiesFactoryFactory


//*****************************************************************************
// Class definition for VySectionPropertiesKeywordFactoryFactory
//*****************************************************************************
class VySectionPropertiesKeywordFactoryFactory : public IStandardNotifier {
public:
   //---------------------------------------------------------------------------
   // Constructors / destructors
   //---------------------------------------------------------------------------
   VySectionPropertiesKeywordFactoryFactory();

   virtual  ~VySectionPropertiesKeywordFactoryFactory();

   //---------------------------------------------------------------------------
   // public member functions
   //---------------------------------------------------------------------------
   VyKeyword * create();

   //---------------------------------------------------------------------------
   // public member data
   //---------------------------------------------------------------------------
   static const INotificationId newObjectCreatedId;

protected:
private:

};   //VySectionPropertiesKeywordFactoryFactory


//*****************************************************************************
// Class definition for VySectionPropertiesLabelPropertiesFactoryFactory
//*****************************************************************************
class VySectionPropertiesLabelPropertiesFactoryFactory : public IStandardNotifier {
public:
   //---------------------------------------------------------------------------
   // Constructors / destructors
   //---------------------------------------------------------------------------
   VySectionPropertiesLabelPropertiesFactoryFactory(unsigned long anId);

   virtual  ~VySectionPropertiesLabelPropertiesFactoryFactory();

   //---------------------------------------------------------------------------
   // public member functions
   //---------------------------------------------------------------------------
   VyLabelProperties * create();

   //---------------------------------------------------------------------------
   // public member data
   //---------------------------------------------------------------------------
   static const INotificationId newObjectCreatedId;

protected:
private:
   //---------------------------------------------------------------------------
   // private member data
   //---------------------------------------------------------------------------
   static unsigned long id;


};   //VySectionPropertiesLabelPropertiesFactoryFactory


//*****************************************************************************
// Class definition for VySectionProperties
//*****************************************************************************
class VySectionProperties : public IFrameWindow, public IObserver {
public:
   //---------------------------------------------------------------------------
   // Constructors / destructors
   //---------------------------------------------------------------------------
   VySectionProperties(
      unsigned long id = WND_VySectionProperties,
      IWindow* parent = IWindow::desktopWindow(),
      IWindow* owner = 0,
      const IRectangle& rect = defaultFramingSpec(),
      const IFrameWindow::Style& style = defaultStyle(),
      const char* title = defaultTitle());

   virtual  ~VySectionProperties();

   //---------------------------------------------------------------------------
   // public member functions
   //---------------------------------------------------------------------------
   static const IRectangle defaultFramingSpec();
   static const IFrameWindow::Style defaultStyle();
   static IString defaultTitle();
   virtual VySectionProperties & initializePart();
   VySectionProperties * getFrameWindow() { return this; };
   IVBVariablePartPointer<VySection *> *  getSection() const { return iSection; };

   //---------------------------------------------------------------------------
   // public member data
   //---------------------------------------------------------------------------
   static const INotificationId readyId;
   static const INotificationId section;

protected:
   //---------------------------------------------------------------------------
   // protected member functions
   //---------------------------------------------------------------------------
   Boolean makeConnections();
   virtual IObserver & dispatchNotificationEvent(const INotificationEvent & anEvent);

private:
   //---------------------------------------------------------------------------
   // private member data
   //---------------------------------------------------------------------------
   IMultiCellCanvas * iMultiCellCanvas;
   IStaticText * iTitleLabel;
   IEntryField * iTitle;
   ICheckBox * iListed;
   IVBContainerControl< VyKeyword*, IVSequence<VyKeyword*>, VySectionPropertiesKeywordContainerCnrObj > * iKeywordContainer;
   IContainerColumn * iKeywordName;
   IContainerColumn * iKeywordListed;
   IContainerColumn * iKeywordExternal;
   ISetCanvas * iKeywordButtons;
   IPushButton * iAddKeyword;
   IPushButton * iModifyKeyword;
   IPushButton * iDeleteKeyword;
   IVBContainerControl< VyLabel*, IVSequence<VyLabel*>, VySectionPropertiesLabelContainerCnrObj > * iLabelContainer;
   IContainerColumn * iLabelName;
   IContainerColumn * iContainerColumn1;
   IContainerColumn * iContainerColumn2;
   ISetCanvas * iLabelButtons;
   IPushButton * iAddLabel;
   IPushButton * iModifyLabel;
   IPushButton * iDeleteLabel;
   IPushButton * iClose;
   IVBVariablePartPointer<VySection *> * iSection;
   VySectionPropertiesLabelFactoryFactory * iLabelFactory;
   VySectionPropertiesKeywordPropertiesFactoryFactory * iKeywordPropertiesFactory;
   IVBVariablePartPointer<VyKeywordProperties *> * iKeywordProperties;
   VySectionPropertiesKeywordFactoryFactory * iKeywordFactory;
   IVBVariablePartPointer<VyLabelProperties *> * iLabelProperties;
   VySectionPropertiesLabelPropertiesFactoryFactory * iLabelPropertiesFactory;
   ExceptionNotification * iExceptionNotification;
   VySectionPropertiesConn0 * conn0;
   VySectionPropertiesConn1 * conn1;
   VySectionPropertiesConn2 * conn2;
   VySectionPropertiesConn3 * conn3;
   VySectionPropertiesConn4 * conn4;
   VySectionPropertiesConn5 * conn5;
   VySectionPropertiesConn7 * conn7;
   VySectionPropertiesConn8 * conn8;
   VySectionPropertiesConn9 * conn9;
   VySectionPropertiesConn10 * conn10;
   VySectionPropertiesConn11 * conn11;
   VySectionPropertiesConn12 * conn12;
   VySectionPropertiesConn27 * conn27;
   VySectionPropertiesConn14 * conn14;
   VySectionPropertiesConn15 * conn15;
   VySectionPropertiesConn16 * conn16;
   VySectionPropertiesConn17 * conn17;
   VySectionPropertiesConn18 * conn18;
   VySectionPropertiesConn19 * conn19;
   VySectionPropertiesConn20 * conn20;
   VySectionPropertiesConn21 * conn21;
   VySectionPropertiesConn24 * conn24;
   VySectionPropertiesConn26 * conn26;
   VySectionPropertiesConn29 * conn29;
   VySectionPropertiesConn23 * conn23;
   VySectionPropertiesConn31 * conn31;
   VySectionPropertiesConn32 * conn32;
   VySectionPropertiesConn33 * conn33;
   VySectionPropertiesConn34 * conn34;
   VySectionPropertiesConn35 * conn35;
   VySectionPropertiesConn36 * conn36;
   VySectionPropertiesConn37 * conn37;
   VySectionPropertiesConn38 * conn38;
   VySectionPropertiesConn39 * conn39;
   VySectionPropertiesConn40 * conn40;
   VySectionPropertiesConn41 * conn41;
   VySectionPropertiesConn42 * conn42;
   VySectionPropertiesConn43 * conn43;
   VySectionPropertiesConn44 * conn44;
   VySectionPropertiesConn45 * conn45;
   VySectionPropertiesConn46 * conn46;

friend class VySectionPropertiesConn33;

#include "VySectionProperties.hpv"
};   //VySectionProperties


/*----------------------------------------------------------------------------*/
/* Resume compiler default packing.                                           */
/*----------------------------------------------------------------------------*/
#pragma pack()

#endif
