/*******************************************************************************
* FILE NAME: VySectionProperties.h                                             *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Constant declarations for class:                                           *
*     VySectionProperties                                                      *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _ICCONST_
#include <icconst.h>
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef WND_VySectionProperties
#define WND_VySectionProperties  VBBASEWINDOWID
#endif

#define WNDOFFSET_VySectionProperties_FrameWindow  0
#define WND_VySectionProperties_FrameWindow  WND_VySectionProperties

#define WND_VySectionProperties_MultiCellCanvas  IC_FRAME_CLIENT_ID

#define WNDOFFSET_VySectionProperties_TitleLabel  1
#define WND_VySectionProperties_TitleLabel  WND_VySectionProperties + WNDOFFSET_VySectionProperties_TitleLabel

#define WNDOFFSET_VySectionProperties_Title  2
#define WND_VySectionProperties_Title  WND_VySectionProperties + WNDOFFSET_VySectionProperties_Title

#define WNDOFFSET_VySectionProperties_Listed  3
#define WND_VySectionProperties_Listed  WND_VySectionProperties + WNDOFFSET_VySectionProperties_Listed

#define WNDOFFSET_VySectionProperties_KeywordContainer  4
#define WND_VySectionProperties_KeywordContainer  WND_VySectionProperties + WNDOFFSET_VySectionProperties_KeywordContainer




#define WNDOFFSET_VySectionProperties_KeywordButtons  5
#define WND_VySectionProperties_KeywordButtons  WND_VySectionProperties + WNDOFFSET_VySectionProperties_KeywordButtons

#define WNDOFFSET_VySectionProperties_AddKeyword  6
#define WND_VySectionProperties_AddKeyword  WND_VySectionProperties + WNDOFFSET_VySectionProperties_AddKeyword

#define WNDOFFSET_VySectionProperties_ModifyKeyword  7
#define WND_VySectionProperties_ModifyKeyword  WND_VySectionProperties + WNDOFFSET_VySectionProperties_ModifyKeyword

#define WNDOFFSET_VySectionProperties_DeleteKeyword  8
#define WND_VySectionProperties_DeleteKeyword  WND_VySectionProperties + WNDOFFSET_VySectionProperties_DeleteKeyword

#define WNDOFFSET_VySectionProperties_LabelContainer  9
#define WND_VySectionProperties_LabelContainer  WND_VySectionProperties + WNDOFFSET_VySectionProperties_LabelContainer




#define WNDOFFSET_VySectionProperties_LabelButtons  10
#define WND_VySectionProperties_LabelButtons  WND_VySectionProperties + WNDOFFSET_VySectionProperties_LabelButtons

#define WNDOFFSET_VySectionProperties_AddLabel  11
#define WND_VySectionProperties_AddLabel  WND_VySectionProperties + WNDOFFSET_VySectionProperties_AddLabel

#define WNDOFFSET_VySectionProperties_ModifyLabel  12
#define WND_VySectionProperties_ModifyLabel  WND_VySectionProperties + WNDOFFSET_VySectionProperties_ModifyLabel

#define WNDOFFSET_VySectionProperties_DeleteLabel  13
#define WND_VySectionProperties_DeleteLabel  WND_VySectionProperties + WNDOFFSET_VySectionProperties_DeleteLabel

#define WNDOFFSET_VySectionProperties_Close  14
#define WND_VySectionProperties_Close  WND_VySectionProperties + WNDOFFSET_VySectionProperties_Close


#define WNDOFFSET_VySectionProperties_LabelFactory  15
#define WND_VySectionProperties_LabelFactory  WND_VySectionProperties + WNDOFFSET_VySectionProperties_LabelFactory

#define WNDOFFSET_VySectionProperties_KeywordPropertiesFactory  15
#define WND_VySectionProperties_KeywordPropertiesFactory  WND_VySectionProperties + WNDOFFSET_VySectionProperties_KeywordPropertiesFactory


#define WNDOFFSET_VySectionProperties_KeywordFactory  22
#define WND_VySectionProperties_KeywordFactory  WND_VySectionProperties + WNDOFFSET_VySectionProperties_KeywordFactory


#define WNDOFFSET_VySectionProperties_LabelPropertiesFactory  22
#define WND_VySectionProperties_LabelPropertiesFactory  WND_VySectionProperties + WNDOFFSET_VySectionProperties_LabelPropertiesFactory



