/*******************************************************************************
* FILE NAME: VySettings.hpp                                                    *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Declaration of the class:                                                  *
*     VySettings- Settings stored in the INI                                   *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _VYSETTINGS_
#define _VYSETTINGS_  

class VySettings;

#ifndef _ISTDNTFY_
#include <istdntfy.hpp>
#endif

class IProfile;
#ifndef FILENAME_HPP
#include <Filename.hpp>
#endif

#ifndef _IWINDOW_
#include <iwindow.hpp>
#endif

#ifndef _IRECT_
#include <irect.hpp>
#endif

#ifndef _ISTRING_
#include <istring.hpp>
#endif

class VySettingsConn0;
class VySettingsConn1;
class VySettingsConn2;
class VySettingsConn3;
class VySettingsConn4;
class VySettingsConn5;
class VySettingsConn6;
class VySettingsConn7;
class VySettingsConn8;
class VySettingsConn9;
class VySettingsConn10;
class VySettingsConn11;
class VySettingsConn12;
class VySettingsConn13;
class VySettingsConn14;
class VySettingsConn15;
class VySettingsConn16;
#include "VySettings.h"


/*----------------------------------------------------------------------------*/
/* Align classes on four byte boundary.                                       */
/*----------------------------------------------------------------------------*/
#pragma pack(4)

//*****************************************************************************
// Class definition for VySettings
//*****************************************************************************
class VySettings : public IStandardNotifier {
public:
   //---------------------------------------------------------------------------
   // Constructors / destructors
   //---------------------------------------------------------------------------
   VySettings();

   virtual  ~VySettings();

   //---------------------------------------------------------------------------
   // public member functions
   //---------------------------------------------------------------------------
   virtual VySettings & initializePart();

   //---------------------------------------------------------------------------
   // public member data
   //---------------------------------------------------------------------------
   static const INotificationId readyId;

protected:
   //---------------------------------------------------------------------------
   // protected member functions
   //---------------------------------------------------------------------------
   Boolean makeConnections();

private:
   //---------------------------------------------------------------------------
   // private member data
   //---------------------------------------------------------------------------
   IProfile * iProfile;
   VySettingsConn0 * conn0;
   VySettingsConn1 * conn1;
   VySettingsConn2 * conn2;
   VySettingsConn3 * conn3;
   VySettingsConn4 * conn4;
   VySettingsConn5 * conn5;
   VySettingsConn6 * conn6;
   VySettingsConn7 * conn7;
   VySettingsConn8 * conn8;
   VySettingsConn9 * conn9;
   VySettingsConn10 * conn10;
   VySettingsConn11 * conn11;
   VySettingsConn12 * conn12;
   VySettingsConn13 * conn13;
   VySettingsConn14 * conn14;
   VySettingsConn15 * conn15;
   VySettingsConn16 * conn16;


#include "VySettings.hpv"
};   //VySettings


/*----------------------------------------------------------------------------*/
/* Resume compiler default packing.                                           */
/*----------------------------------------------------------------------------*/
#pragma pack()

#endif
