/*******************************************************************************
* FILE NAME: VySymbol.cpp                                                      *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Class implementation of the class:                                         *
*     VySymbol- Typographic symbol                                             *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _INOTIFEV_
#include <inotifev.hpp>
#endif

#ifndef _IOBSERVR_
#include <iobservr.hpp>
#endif

#ifndef _ISTDNTFY_
#include <istdntfy.hpp>
#endif

#ifndef _VYSYMBOL_
#include "VySymbol.hpp"
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef _ITRACE_
#include <itrace.hpp>
#endif


#pragma export (VySymbol::readyId)
const INotificationId VySymbol::readyId = "VySymbol::readyId";

//------------------------------------------------------------------------------
// VySymbol :: VySymbol
//------------------------------------------------------------------------------
#pragma export (VySymbol::VySymbol())
VySymbol::VySymbol()
{

   construct();
}     //end constructor


//------------------------------------------------------------------------------
// VySymbol :: ~VySymbol
//------------------------------------------------------------------------------
#pragma export (VySymbol::~VySymbol())
VySymbol::~VySymbol()
{
   destruct();

}

//------------------------------------------------------------------------------
// VySymbol :: initializePart
//------------------------------------------------------------------------------
#pragma export (VySymbol::initializePart())
VySymbol & VySymbol::initializePart()
{
   makeConnections();
   notifyObservers(INotificationEvent(readyId, *this));
   return *this;
}


//------------------------------------------------------------------------------
// VySymbol :: makeConnections
//------------------------------------------------------------------------------
#pragma export (VySymbol::makeConnections())
Boolean VySymbol::makeConnections()
{
   this->enableNotification();

   return true;
}


#include "VySymbol.cpv"
