/*******************************************************************************
* FILE NAME: VySymbolSelector.h                                                *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Constant declarations for class:                                           *
*     VySymbolSelector- Symbol selection list                                  *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _ICCONST_
#include <icconst.h>
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef WND_VySymbolSelector
#define WND_VySymbolSelector  VBBASEWINDOWID
#endif

#define WNDOFFSET_VySymbolSelector_FrameWindow  0
#define WND_VySymbolSelector_FrameWindow  WND_VySymbolSelector

#define WND_VySymbolSelector_Symbols  IC_FRAME_CLIENT_ID


