/*******************************************************************************
* FILE NAME: VyWait.h                                                          *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Constant declarations for class:                                           *
*     VyWait- Progress and status indicator                                    *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _ICCONST_
#include <icconst.h>
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef WND_VyWait
#define WND_VyWait  VBBASEWINDOWID
#endif

#define WNDOFFSET_VyWait_FrameWindow  0
#define WND_VyWait_FrameWindow  WND_VyWait

#define WND_VyWait_SetCanvas1  IC_FRAME_CLIENT_ID

#define WNDOFFSET_VyWait_Task  1
#define WND_VyWait_Task  WND_VyWait + WNDOFFSET_VyWait_Task

#define WNDOFFSET_VyWait_Status  2
#define WND_VyWait_Status  WND_VyWait + WNDOFFSET_VyWait_Status

#define WNDOFFSET_VyWait_ProgressIndicator  3
#define WND_VyWait_ProgressIndicator  WND_VyWait + WNDOFFSET_VyWait_ProgressIndicator

#define WNDOFFSET_VyWait_ErrorList  4
#define WND_VyWait_ErrorList  WND_VyWait + WNDOFFSET_VyWait_ErrorList

#define WNDOFFSET_VyWait_OK  5
#define WND_VyWait_OK  WND_VyWait + WNDOFFSET_VyWait_OK


