
all: \
    .\ipfparse.lib

.\StringPair.obj: \
    d:\proj\ipfparse\StringPair.cpp \
    {d:\proj\ipfparse;$(INCLUDE);}StringPair.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}StringPair.ipp

.\PanelLink.obj: \
    d:\proj\ipfparse\PanelLink.cpp \
    {d:\proj\ipfparse;$(INCLUDE);}PanelLink.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}PanelLink.ipp

.\IpfYacc.obj: \
    d:\proj\ipfparse\IpfYacc.cpp \
    {d:\proj\ipfparse;$(INCLUDE);}SymbolLookup.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}Symbol.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}SymbolLookup.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}CodePage.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}Symbol.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}CodePage.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}Footnote.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}WindowDef.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}Gin.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}Footnote.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}Distance.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}WindowDef.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}MekTek.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}FontInfo.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}Gin.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}Distance.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}FontInfo.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}ParserIndicator.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}IpfYacc.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}IpfParser.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}ParserIndicator.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}EnhancedYacc.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}Parser.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}Filename.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}StringPair.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}PanelLink.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}IpfParser.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}Parser.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}StringPair.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}PanelLink.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}ipf.yhh

.\IpfParser.obj: \
    d:\proj\ipfparse\IpfParser.cpp \
    {d:\proj\ipfparse;$(INCLUDE);}SymbolLookup.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}Symbol.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}SymbolLookup.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}CodePage.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}Symbol.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}CodePage.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}Generator.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}Footnote.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}Registration.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}CurrentDate.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}WindowDef.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}ArtDef.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}Gin.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}Generator.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}Footnote.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}UserKey.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}Registration.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}Distance.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}WindowDef.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}MekTek.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}ArtDef.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}FontInfo.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}Gin.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}ExpirationDate.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}UserKey.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}Distance.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}FontInfo.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}ExpirationDate.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}ParserIndicator.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}ParserException.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}IpfYacc.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}IpfParser.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}ParserIndicator.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}EnhancedYacc.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}Parser.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}Filename.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}StringPair.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}PanelLink.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}IpfParser.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}Parser.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}StringPair.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}PanelLink.ipp

.\Footnote.obj: \
    d:\proj\ipfparse\Footnote.cpp \
    {d:\proj\ipfparse;$(INCLUDE);}Symbol.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}CodePage.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}Symbol.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}CodePage.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}Generator.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}Footnote.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}Registration.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}CurrentDate.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}WindowDef.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}ArtDef.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}Gin.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}Generator.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}Footnote.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}UserKey.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}Registration.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}Distance.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}WindowDef.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}MekTek.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}ArtDef.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}FontInfo.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}Gin.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}ExpirationDate.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}UserKey.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}Distance.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}FontInfo.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}ExpirationDate.ipp

.\SymbolLookup.obj: \
    d:\proj\ipfparse\SymbolLookup.cpp \
    {d:\proj\ipfparse;$(INCLUDE);}SymbolLookup.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}Symbol.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}SymbolLookup.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}CodePage.hpp \
    {d:\proj\ipfparse;$(INCLUDE);}Symbol.ipp \
    {d:\proj\ipfparse;$(INCLUDE);}CodePage.ipp
