VyperHelp is a visual outliner and editor for creating online help for OS/2-based systems.  It generates IPF files, as well as WinHelp, HTML, and HTMLHelp. VyperHelp has the following features:

   WYSIWYG text editing with codes revealed
   Powerful outline tree controls
   Keyword/index support
   Full symbol support
   IPF import and export
   HTML export (single file or frames)
   HTMLHelp export
   WinHelp (HPJ,RTF,CNT) import and export
   RTF document-style export
   ASCII text import and export
   Command-line conversion program

