
all: \
    .\ipfgen.lib

.\IPF_Send.asm .\IPF_Send.obj: \
    d:\proj\IPFGenerator\IPF_Send.cpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_Common.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}MekTek.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPFGenerator.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_Index.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_Context.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_LabelList.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Generator.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CodePage.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Gin.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Registration.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CurrentDate.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}WindowDef.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ArtDef.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Generator.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CodePage.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Distance.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Symbol.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}FontInfo.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Gin.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}UserKey.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Registration.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}WindowDef.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ArtDef.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Distance.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Symbol.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}FontInfo.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ExpirationDate.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}UserKey.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ExpirationDate.ipp

.\IPF_Section.asm .\IPF_Section.obj: \
    d:\proj\IPFGenerator\IPF_Section.cpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_Common.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}MekTek.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPFGenerator.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_Index.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_Context.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_LabelList.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Generator.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CodePage.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Gin.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Registration.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CurrentDate.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}WindowDef.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ArtDef.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Generator.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CodePage.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Distance.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Symbol.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}FontInfo.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Gin.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}UserKey.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Registration.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}WindowDef.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ArtDef.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Distance.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Symbol.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}FontInfo.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ExpirationDate.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}UserKey.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ExpirationDate.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IpfForwarder.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IpfForwarder.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IpfForwarderSequence.hpp

.\IPF_ParaStyle.asm .\IPF_ParaStyle.obj: \
    d:\proj\IPFGenerator\IPF_ParaStyle.cpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_Common.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}MekTek.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPFGenerator.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_Index.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_Context.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_LabelList.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Generator.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CodePage.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Gin.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Registration.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CurrentDate.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}WindowDef.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ArtDef.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Generator.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CodePage.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Distance.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Symbol.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}FontInfo.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Gin.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}UserKey.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Registration.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}WindowDef.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ArtDef.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Distance.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Symbol.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}FontInfo.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ExpirationDate.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}UserKey.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ExpirationDate.ipp

.\IPF_Keyword.asm .\IPF_Keyword.obj: \
    d:\proj\IPFGenerator\IPF_Keyword.cpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_Common.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}MekTek.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPFGenerator.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_Index.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_Context.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_LabelList.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Generator.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CodePage.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Gin.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Registration.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CurrentDate.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}WindowDef.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ArtDef.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Generator.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CodePage.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Distance.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Symbol.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}FontInfo.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Gin.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}UserKey.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Registration.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}WindowDef.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ArtDef.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Distance.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Symbol.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}FontInfo.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ExpirationDate.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}UserKey.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ExpirationDate.ipp

.\IPF_Generator.asm .\IPF_Generator.obj: \
    d:\proj\IPFGenerator\IPF_Generator.cpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_Common.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}MekTek.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPFGenerator.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_Index.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_Context.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_LabelList.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Generator.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CodePage.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Gin.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Registration.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CurrentDate.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}WindowDef.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ArtDef.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Generator.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CodePage.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Distance.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Symbol.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}FontInfo.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Gin.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}UserKey.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Registration.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}WindowDef.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ArtDef.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Distance.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Symbol.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}FontInfo.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ExpirationDate.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}UserKey.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ExpirationDate.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IpfForwarder.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IpfForwarder.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IpfForwarderSequence.hpp

.\IPF_Distance.asm .\IPF_Distance.obj: \
    d:\proj\IPFGenerator\IPF_Distance.cpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_Common.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}MekTek.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPFGenerator.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_Index.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_Context.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_LabelList.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Generator.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CodePage.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Gin.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Registration.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CurrentDate.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}WindowDef.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ArtDef.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Generator.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CodePage.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Distance.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Symbol.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}FontInfo.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Gin.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}UserKey.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Registration.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}WindowDef.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ArtDef.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Distance.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Symbol.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}FontInfo.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ExpirationDate.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}UserKey.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ExpirationDate.ipp

.\IPF_Control.asm .\IPF_Control.obj: \
    d:\proj\IPFGenerator\IPF_Control.cpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_Common.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}MekTek.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPFGenerator.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_Index.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_Context.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_LabelList.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Generator.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CodePage.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Gin.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Registration.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CurrentDate.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}WindowDef.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ArtDef.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Generator.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CodePage.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Distance.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Symbol.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}FontInfo.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Gin.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}UserKey.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Registration.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}WindowDef.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ArtDef.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Distance.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Symbol.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}FontInfo.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ExpirationDate.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}UserKey.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ExpirationDate.ipp

.\IPF_Context.asm .\IPF_Context.obj: \
    d:\proj\IPFGenerator\IPF_Context.cpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_Common.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}MekTek.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPFGenerator.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_Index.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_Context.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_LabelList.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Generator.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CodePage.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Gin.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Registration.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CurrentDate.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}WindowDef.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ArtDef.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Generator.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CodePage.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Distance.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Symbol.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}FontInfo.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Gin.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}UserKey.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Registration.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}WindowDef.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ArtDef.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Distance.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Symbol.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}FontInfo.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ExpirationDate.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}UserKey.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ExpirationDate.ipp

.\IPF_CharStyle.asm .\IPF_CharStyle.obj: \
    d:\proj\IPFGenerator\IPF_CharStyle.cpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_Common.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}MekTek.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPFGenerator.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_Index.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_Context.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_LabelList.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Generator.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CodePage.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Gin.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Registration.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CurrentDate.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}WindowDef.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ArtDef.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Generator.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CodePage.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Distance.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Symbol.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}FontInfo.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Gin.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}UserKey.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Registration.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}WindowDef.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ArtDef.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Distance.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Symbol.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}FontInfo.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ExpirationDate.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}UserKey.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ExpirationDate.ipp

.\IPF_Art.asm .\IPF_Art.obj: \
    d:\proj\IPFGenerator\IPF_Art.cpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_Common.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}MekTek.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPFGenerator.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_Index.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_Context.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_LabelList.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Generator.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CodePage.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Gin.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Registration.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CurrentDate.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}WindowDef.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ArtDef.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Generator.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CodePage.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Distance.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Symbol.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}FontInfo.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Gin.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}UserKey.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Registration.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}WindowDef.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ArtDef.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Distance.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Symbol.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}FontInfo.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ExpirationDate.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}UserKey.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ExpirationDate.ipp

.\IpfForwarderSequence.asm .\IpfForwarderSequence.obj: \
    d:\proj\IPFGenerator\IpfForwarderSequence.cpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CodePage.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Gin.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CodePage.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Distance.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Symbol.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}FontInfo.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Gin.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Distance.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Symbol.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}FontInfo.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IpfForwarder.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IpfForwarder.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IpfForwarderSequence.hpp

.\IpfForwarder.asm .\IpfForwarder.obj: \
    d:\proj\IPFGenerator\IpfForwarder.cpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CodePage.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Gin.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CodePage.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Distance.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Symbol.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}FontInfo.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Gin.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Distance.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Symbol.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}FontInfo.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IpfForwarder.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IpfForwarder.ipp

.\IPF_Symbols.asm .\IPF_Symbols.obj: \
    d:\proj\IPFGenerator\IPF_Symbols.cpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_Common.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}MekTek.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPFGenerator.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_Index.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_Context.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}IPF_LabelList.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Generator.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CodePage.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Gin.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Registration.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CurrentDate.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}WindowDef.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ArtDef.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Generator.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}CodePage.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Distance.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Symbol.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}FontInfo.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Gin.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}UserKey.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Registration.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}WindowDef.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ArtDef.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Distance.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}Symbol.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}FontInfo.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ExpirationDate.hpp \
    {d:\proj\IPFGenerator;$(INCLUDE);}UserKey.ipp \
    {d:\proj\IPFGenerator;$(INCLUDE);}ExpirationDate.ipp
